In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [7]:
np.empty(3)

array([4.63579467e-310, 0.00000000e+000, 1.58101007e-322])

In [9]:
np.arange(4)

array([0, 1, 2, 3])

In [10]:
#setting jump size:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [13]:
#spaced linearly in a specific interval:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
array = np.ones(2, dtype=int)
array

array([1, 1])

In [15]:
type(array[0])

numpy.int64

In [16]:
type(array)

numpy.ndarray

### Adding, removing, and sorting elements

np.append()

np.delete()

np.sort()

In [23]:
arr = np.array([1,2,3,4,5,6,7,8])

In [24]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [26]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
arr = np.append(arr, [1,2])

In [28]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [29]:
np.delete(arr, len(arr)-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 1])

In [30]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [31]:
arr = np.delete(arr, len(arr)-1)

In [32]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 1])

In [34]:
arr = np.delete(arr, len(arr)-1)

In [35]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
#sorting example:
arr = np.array([9,5,0,2,96,4,2,44,1])
np.sort(arr)

array([ 0,  1,  2,  2,  4,  5,  9, 44, 96])

In [6]:
# notice they are all not affecting the np array, unlss we reassign
arr

array([ 9,  5,  0,  2, 96,  4,  2, 44,  1])

### Shape and size of an array

ndarray.ndim()

ndarray.size()

ndarray.shape()

In [8]:
array_example = np.array([[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]]])

In [9]:
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [11]:
array_example[0][1]

array([4, 5, 6, 7])

In [12]:
array_example[1][1]

array([4, 5, 6, 7])

In [14]:
array_example[2][0]

array([0, 1, 2, 3])

In [15]:
#number of dimentions:
array_example.ndim

3

In [16]:
#total elements in ana array:
array_example.size

24

In [17]:
array_example.shape

(3, 2, 4)

### Reshaping an Array

np.reshape()

param:
numpy.reshape(a,newshape, order)

In [3]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [4]:
b = a.reshape(3,2) # reshaping to have 3 rows and 2 columns
print(b)

[[0 1]
 [2 3]
 [4 5]]


### Convert 1D array to 2D array (How to add new axis to an array?)

np.newaxis

np.expand_dims

In [5]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [6]:
npa2 = a[np.newaxis]
a2.shape

(1, 6)

In [7]:
##can convert a 1D array with either row vector or a column vector using np.newaxis
#below, inserting a an axis along the first dimention to convert a 1D array to a row vector
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [8]:
#for column vector, insert an axis along the second dimention
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [11]:
#expand an array by inserting new axis at a specified position with: np.expand_dims
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [12]:
#adding an axis at index position 1 using np.expand_dims
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [15]:
#at position zero:
c = np.expand_dims(a,axis=0)
c.shape

(1, 6)

INDEXING AND SLICING NUMPY ARRAYS, SAME AS INDEXING AND SLICING PYTHON LISTS

In [16]:
data = np.array([1,2,3])

print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

1
2
[1 2]
[2 3]
[2 3]


In [17]:
#subset, slice and/or index help to take a section of array and copy it for further use and applying additional operations on it

a = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])

In [19]:
#printing all values less than 5:
print(a[a<5])
print(a[a>6])

[1 2 3 4]
[ 7  8  9 10 11 12]


In [32]:
#selecting numbers equal to or greater than 5, and using a conditional to index an array
five_up = (a>=5)
print(a[five_up])


##checking for a number divisible by another
divisible_by_2 = (a%2==0)
print(a[divisible_by_2])

#or a more direct way of writing it:
divisible_by_3 = a[a%3 == 0]
print(divisible_by_3)

[ 5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12]
[ 3  6  9 12]


In [35]:
# selecting elements that satisfy multiple conditions is done with & and |
# unlike python that uses: "and" "or" and JavaScript that uses && ||
c = a[(a>2) & (a<11)]
print(c)

#using the | (or):
d = a[(a>=6) | (a==2arrayarrayarray)]
print(d)

[ 3  4  5  6  7  8  9 10]
[ 2  6  7  8  9 10 11 12]


In [37]:
five_up = (a> 5) | (aarray == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [39]:
#using np.where() to select elements or indices from an array
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
#printing indices of elements that are less than 5:
b = np.where(a<5)
print(b)
#this returns a tuple of arrays, one for each dimension
# the first represents the row indices where these valeus were found
# the second array respresents the column indices where the values are found

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [40]:
#generating a list of coordinates where the above elements exist
# zip the arrays then iterate over the list of coordinates and print them
list_of_coordinates = list(zip(b[0],b[1]))

for coor in list_of_coordinates:
    print(coor)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [43]:
#np.where() can also be used to print the elements in an array
# here will print elements less than 5 with where():
#remember that b uses tha np.where(), will reference it to print the elements
print(a[b])

#same result in this case as saying
print(a[a<5])

[1 2 3 4]
[1 2 3 4]


## Creating an Array from existing Data